In [6]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mesa_reader
from plotly.subplots import make_subplots
import math
import plotly.graph_objects as go
import plotly.io as pio
import plotly.offline as pyo

pio.templates.default = "plotly"

It should be noted that `core_mass` is calculated as the mass of the outermost `burning` zone AKA the first zone fully within the core.

Core compositions calculations are a bit more complicated. We need to sum over the core zones and produce a mass fraction for each element.

It goes something like this:

$$\frac{1}{m_*}\sum_{i=n_i}^{n_f} (m_i \times x_i)$$

Where:

$
\begin{align}
m_* &= \text{The mass of the star in kg} \\
n_i &= \text{The first zone in the core} \\
n_f &= \text{The last zone in the core} \\
m_i &= \text{The mass of the zone in kg} \\
x_i &= \text{The mass fraction of the element in the zone}
\end{align}
$

This is repeated for each element.

In [7]:
SOLAR_MASS = 1.989 * 10 ** 30  # kg
SOLAR_RADIUS = 696340 * 1000  # m

elements = {
    'h1': 'H',
    'he3': 'He3',
    'he4': 'He',
    'c12': 'C',
    'n14': 'N',
    'o16': 'O',
    'ne20': 'Ne',
    'mg24': 'Mg',
}


HE3_MASS = 3.016029
ATOMIC_UNIT = 1.6605402e-27  # kg

## Data object for stellar profiles, including detailed temperature-density profiles, core radius/mass, reaction rates, composition, etc.
class Zone:
    def __init__(self, zone_number, thickness, top, temperature, mass, next_zone_mass, reaction_rates,
                 composition: dict[str, float]):
        """
        :param zone_number: Number of the zone
        :param thickness: Thickness of the zone in log10 cm
        :param top: Radius at outer boundary of the zone in log10 Rsun
        :param temperature: Temperature at the center of the zone in log10 K
        :param mass: Mass from the outer edge of the zone to the center in log10 Msun
        :param next_zone_mass: Mass from the outer edge of the next zone inwards to the center of the star in log10 Msun
        :param reaction_rates: Raw reactions/second of he3+he3->h1+h1+he4 in the zone
        :param composition: Mass fractions of the zone
        """

        self.zone_number = zone_number
        self.thickness = (10 ** thickness) / 100  # log10 cm => m
        self.top = (10 ** top) * SOLAR_RADIUS  # log10 Rsun => m
        bottom = self.top - self.thickness  # m
        self.temperature = 10 ** temperature  # log10 K => K
        self.mass = (mass - next_zone_mass) * SOLAR_MASS  # Msun => kg
        self.mass_coordinate = mass * SOLAR_MASS  # Msun => kg
        self.reaction_rates = reaction_rates
        self.composition = composition

        self.volume = 4 / 3 * np.pi * (np.power(self.top, 3) - np.power(bottom, 3))  # Volume of the shell, m^3
        self.density = self.mass / self.volume  # kg/m^3

        self.he3_number_density = (self.composition['He3'] * self.density) / (HE3_MASS * ATOMIC_UNIT)

    def to_record(self):
        record = {
            'zone_number': self.zone_number,
            'thickness': self.thickness,
            'top': self.top,
            'temperature': self.temperature,
            'mass': self.mass,
            'reaction_rates': self.reaction_rates,
            'volume': self.volume,
            'density': self.density,
            'he3_number_density': self.he3_number_density,
        }

        for element in self.composition:
            record[element] = self.composition[element]

        return record

    def as_profile_record(self):
        return {
            'core_temperature': self.temperature,
            'core_density': self.density,
            'reaction_rates_per_unit_volume': self.reaction_rates / self.volume,
        }


class StellarProfile:
    def __init__(self, source_id, batch_idx, iteration_idx, mass, core_radius, radius, original_radius, age,
                 original_age, zones: list[Zone]):
        """
        :param source_id: Source ID of the star
        :param batch_idx: Batch index of the simulation
        :param iteration_idx: Iteration index of the simulation
        :param mass: Mass of the star in Msun
        :param core_radius: Radius of the core in log10 Rsun
        :param core_radius: Size of core relative to the simulation radius (which is in log10 Rsun)
        :param radius: Radius of the simulated star in log10 Rsun
        :param original_radius: Original radius of the star for error calculations Rsun
        :param age: Age of the simulated star in years
        :param original_age: Original age of the star for error calculations
        :param zones: All profile zones, will be filtered to only include the core
        """

        self.source_id = source_id
        self.batch_idx = batch_idx
        self.iteration_idx = iteration_idx
        self.mass = mass * SOLAR_MASS  # Msun => kg
        self.radius = (10 ** radius) * SOLAR_RADIUS  # log10 Rsun => m
        self.normalized_core_radius = core_radius
        self.core_radius = core_radius * self.radius  # Normalized (Rsun) => m
        self.original_radius = original_radius * SOLAR_RADIUS  # Rsun => m
        self.age = age
        self.original_age = original_age

        burning_zones = []
        records = []

        for zone in zones:
            if zone.top < self.core_radius:
                burning_zones.append(zone)
                records.append(zone.to_record())

        ### Sort by zone numbers
        burning_zones.sort(key=lambda x: x.zone_number)

        self.burning_zones = pd.DataFrame(records)

        ### Calculate core mass
        self.core_mass = self.burning_zones['mass'].sum()

        self.core_volume = 4 / 3 * np.pi * np.power(self.core_radius, 3)  # m^3
        self.core_density = (self.burning_zones['density'] * self.burning_zones['mass']).sum() / self.core_mass
        self.core_temperature = (self.burning_zones['temperature'] * self.burning_zones['mass']).sum() / self.core_mass

        self.reaction_rates = self.burning_zones['reaction_rates'].sum()
        self.reaction_rates_per_unit_volume = self.reaction_rates / self.core_volume  # reactions/second/m^3

        self.he3_number_density = (self.burning_zones['he3_number_density'] * self.burning_zones['mass']).sum() / self.core_mass

        # Core composition
        self.composition = {}

        for element in elements.values():
            self.composition[element] = 0
            mass_sum = (self.burning_zones[element] * self.burning_zones['mass']).sum()
            self.composition[element] = mass_sum / self.core_mass

    @staticmethod
    def error(original, calculated):
        return (calculated - original) / original

    def to_record(self):
        original_core_radius = self.normalized_core_radius * self.original_radius
        original_volume = 4 / 3 * np.pi * np.power(original_core_radius, 3)
        original_reaction_rates_per_unit_volume = self.reaction_rates / original_volume

        record = {
            'source_id': self.source_id,
            'batch_idx': self.batch_idx,
            'iteration_idx': self.iteration_idx,
            'mass': self.mass,
            'core_radius': self.core_radius,
            'core_radius_error': StellarProfile.error(original_core_radius, self.core_radius),
            'original_core_radius': original_core_radius,
            'radius': self.radius,
            'radius_error': StellarProfile.error(self.original_radius, self.radius),
            'original_radius': self.original_radius,
            'age': self.age,
            'original_age': self.original_age,
            'age_error': StellarProfile.error(self.original_age, self.age),
            'core_mass': self.core_mass,
            'core_volume': self.core_volume,
            'core_volume_error': StellarProfile.error(original_volume, self.core_volume),
            'original_core_volume': original_volume,
            'core_density': self.core_density,
            'core_temperature': self.core_temperature,
            'reaction_rates_per_unit_volume': self.reaction_rates_per_unit_volume,
            'reaction_rates_error': StellarProfile.error(original_reaction_rates_per_unit_volume,
                                                         self.reaction_rates_per_unit_volume),
            'original_reaction_rates_per_unit_volume': original_reaction_rates_per_unit_volume,
            'burning_zones': self.burning_zones.to_dict(orient='records'),
            'he3_number_density': self.he3_number_density,
        }

        for element in self.composition:
            record[element] = self.composition[element]

        return record

    def temperature_density_profile(self):
        densities = self.burning_zones['density']
        temperatures = self.burning_zones['temperature']
        radii = self.burning_zones['top']

        return [radii, temperatures, densities]

    def temperature_density_profile_2d(self):
        densities = self.burning_zones['density']
        temperatures = self.burning_zones['temperature']

        return [densities, temperatures]

    def temperature_profile(self):
        temperatures = self.burning_zones['temperature']
        radii = self.burning_zones['top']

        return [radii, temperatures]

    def density_profile(self):
        densities = self.burning_zones['density']
        radii = self.burning_zones['top']

        return [radii, densities]

## Parsing simulation history files
In the `simulate/LOGS` directory, all of the simulation output files are stored (one directory per thread).

The first five lines are not needed, so we will skip them.
The sixth line is the header, which contains the column names.
The last line is the latest output, which contains the final values.

In [8]:
output_headers = ['source_id', 'batch_idx', 'iteration_idx', 'radius', 'e_radius', 'mass', 'e_mass', 'age', 'y', 'z',
                  'log_cntr_P', 'log_cntr_Rho', 'log_cntr_T', 'core_radius', 'core_mass',
                  'H', 'He3', 'He', 'C', 'N', 'O', 'Ne', 'Mg', 'pp_rate']
output = []

profiles = {}  # source_id -> StellarProfile

records = []

all_zones = []

for directory in os.scandir('simulate/LOGS'):
    dir_name = directory.name
    thread_num = int(dir_name.split('/')[-1])
    _data = pd.read_csv(f'simulate/run/{thread_num}/data.csv', dtype={'source_id': str})  # Source data
    path = Path(f'simulate/LOGS/{dir_name}')

    for dir in path.iterdir():
        idx = int(dir.name)

        data = mesa_reader.MesaLogDir(f'simulate/LOGS/{dir_name}/{idx}', memoize_profiles=False)

        history_data: mesa_reader.MesaData = data.history_data
        last_profile: mesa_reader.MesaData = data.profile_data()

        row_data = []
        headers = []

        for i in history_data.bulk_data[-1]:
            row_data.append(i)

        for i in history_data.bulk_names:
            headers.append(i)

        df = pd.DataFrame([row_data], columns=headers)
        row = _data.iloc[idx]
        core_radius = 0

        radius = df['log_R'].iloc[-1]
        original_radius = row['radius']

        age = df['star_age'].iloc[-1]
        original_age = row['age']

        for i in range(1, 10):
            burn_type = int(df[f'burn_relr_type_{i}'].iloc[-1])
            val = float(df[f'burn_relr_top_{i}'].iloc[-1])
            if burn_type != -9999 and val != 1 and val > 0:
                core_radius = val
            elif burn_type == -9999 and val == 1:
                break

        profile_data_raw = pd.DataFrame(last_profile.bulk_data, columns=last_profile.bulk_names)
        profile_data_raw['next_mass'] = profile_data_raw['mass'].shift(-1)
        profile_data_raw['next_mass'].fillna(0, inplace=True)

        zones = []

        log_dr_array = profile_data_raw['log_dr'].values
        logR_array = profile_data_raw['logR'].values
        logT_array = profile_data_raw['logT'].values
        mass_array = profile_data_raw['mass'].values
        next_mass_array = profile_data_raw['next_mass'].values
        raw_rate_array = profile_data_raw['raw_rate_r_he3_he3_to_h1_h1_he4'].values

        element_names = list(elements.keys())
        element_columns = {el: profile_data_raw[el].values for el in element_names}
        element_mapped_names = [elements[el] for el in element_names]

        for i in range(len(profile_data_raw)):
            composition = {element_mapped_names[j]: element_columns[element_names[j]][i] for j in
                           range(len(element_names))}
            top = logR_array[i]
            zone = Zone(
                zone_number=profile_data_raw.index[i],
                thickness=log_dr_array[i],
                top=top,
                temperature=logT_array[i],
                mass=mass_array[i],
                next_zone_mass=next_mass_array[i],
                reaction_rates=raw_rate_array[i],
                composition=composition,
            )

            # r = (10 ** radius) * SOLAR_RADIUS * core_radius
            #
            # if top < r:
            #     all_zones.append(zone.as_profile_record())

            # Append a new Zone
            zones.append(zone)

        profile = StellarProfile(row['source_id'], int(dir_name), idx, row['mass'], core_radius, radius,
                                 original_radius, age, original_age, zones)

        records.append(profile.to_record())
        profiles[row['source_id']] = profile

        print(f'Finished {dir_name}/{idx} ({len(records)} processed)')

df = pd.DataFrame(records)
df.set_index('source_id', inplace=True)

# zone_df = pd.DataFrame(all_zones)

Finished 0/0 (1 processed)
Finished 0/1 (2 processed)
Finished 0/10 (3 processed)
Finished 0/100 (4 processed)
Finished 0/101 (5 processed)
Finished 0/102 (6 processed)
Finished 0/103 (7 processed)
Finished 0/104 (8 processed)
Finished 0/105 (9 processed)
Finished 0/106 (10 processed)
Finished 0/107 (11 processed)
Finished 0/108 (12 processed)
Finished 0/109 (13 processed)
Finished 0/11 (14 processed)
Finished 0/110 (15 processed)
Finished 0/111 (16 processed)
Finished 0/112 (17 processed)
Finished 0/113 (18 processed)
Finished 0/114 (19 processed)
Finished 0/115 (20 processed)
Finished 0/116 (21 processed)
Finished 0/117 (22 processed)
Finished 0/118 (23 processed)
Finished 0/119 (24 processed)
Finished 0/12 (25 processed)
Finished 0/120 (26 processed)
Finished 0/121 (27 processed)
Finished 0/122 (28 processed)
Finished 0/123 (29 processed)
Finished 0/124 (30 processed)
Finished 0/125 (31 processed)
Finished 0/126 (32 processed)
Finished 0/127 (33 processed)
Finished 0/128 (34 processed)
Finished 0/129 (35 processed)
Finished 0/13 (36 processed)
Finished 0/130 (37 processed)
Finished 0/131 (38 processed)
Finished 0/132 (39 processed)
Finished 0/133 (40 processed)
Finished 0/134 (41 processed)
Finished 0/135 (42 processed)
Finished 0/136 (43 processed)
Finished 0/137 (44 processed)
Finished 0/138 (45 processed)
Finished 0/139 (46 processed)
Finished 0/14 (47 processed)
Finished 0/140 (48 processed)
Finished 0/141 (49 processed)
Finished 0/142 (50 processed)
Finished 0/143 (51 processed)
Finished 0/144 (52 processed)
Finished 0/145 (53 processed)
Finished 0/146 (54 processed)
Finished 0/147 (55 processed)
Finished 0/148 (56 processed)
Finished 0/149 (57 processed)
Finished 0/15 (58 processed)
Finished 0/150 (59 processed)
Finished 0/151 (60 processed)
Finished 0/152 (61 processed)
Finished 0/153 (62 processed)
Finished 0/154 (63 processed)
Finished 0/155 (64 processed)
Finished 0/156 (65 processed)
Finished 0/157 (66 processed)
Finished 0/158 (67 processed)
Finished 0/159 (68 processed)
Finished 0/16 (69 processed)
Finished 0/160 (70 processed)
Finished 0/161 (71 processed)
Finished 0/162 (72 processed)
Finished 0/163 (73 processed)
Finished 0/164 (74 processed)
Finished 0/165 (75 processed)
Finished 0/166 (76 processed)
Finished 0/167 (77 processed)
Finished 0/168 (78 processed)
Finished 0/169 (79 processed)
Finished 0/17 (80 processed)
Finished 0/170 (81 processed)
Finished 0/171 (82 processed)
Finished 0/172 (83 processed)
Finished 0/173 (84 processed)
Finished 0/174 (85 processed)
Finished 0/175 (86 processed)
Finished 0/176 (87 processed)
Finished 0/177 (88 processed)
Finished 0/178 (89 processed)
Finished 0/179 (90 processed)

KeyboardInterrupt:

In [ ]:
df.to_json('./stellar_profiles.json', orient='index')
df

In [9]:
df = pd.read_json('./stellar_profiles.json', orient='index')
df.index = df.index.astype(np.int64)
df

C:\Users\maxiw\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:189: RuntimeWarning:

invalid value encountered in cast

,batch_idx,iteration_idx,mass,core_radius,core_radius_error,original_core_radius,radius,radius_error,original_radius,age,...,burning_zones,he3_number_density,H,He3,He,C,N,O,Ne,Mg
2268469823008193152,0,0,1.637225e+30,1.179559e+08,-0.030944,1.217226e+08,5.890937e+08,-0.030944,6.079048e+08,1.299812e+10,...,"[{'zone_number': 697, 'thickness': 741941.5974...",2.482972e+27,0.527613,0.000213,0.453644,0.000878,0.003552,0.008506,0.001893,0.003701
2264752202396093440,0,1,1.621123e+30,1.188506e+08,0.021081,1.163968e+08,5.827517e+08,0.021081,5.707203e+08,1.114927e+10,...,"[{'zone_number': 696, 'thickness': 710542.9248...",2.835426e+27,0.552919,0.000242,0.433907,0.000684,0.002398,0.005943,0.001322,0.002586
2268087910219685504,0,10,1.445228e+30,1.009805e+08,-0.006525,1.016437e+08,4.962256e+08,-0.006525,4.994847e+08,1.233394e+10,...,"[{'zone_number': 704, 'thickness': 1505962.507...",4.950885e+27,0.580995,0.000380,0.402323,0.001233,0.002598,0.007527,0.001673,0.003271
1244590404650553600,0,100,1.895295e+30,1.382939e+08,0.063856,1.299931e+08,7.505098e+08,0.063856,7.054621e+08,7.745124e+09,...,"[{'zone_number': 692, 'thickness': 1474306.763...",1.487067e+27,0.539005,0.000155,0.446877,0.000525,0.002917,0.006308,0.001425,0.002787
6242646355272876928,0,101,1.823523e+30,1.321363e+08,-0.045321,1.384092e+08,6.934996e+08,-0.045321,7.264219e+08,9.557687e+09,...,"[{'zone_number': 695, 'thickness': 1503402.030...",1.612348e+27,0.525019,0.000157,0.457315,0.000648,0.003613,0.007968,0.001786,0.003493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406352685632976768,3,95,2.026285e+30,1.473643e+08,0.050809,1.402388e+08,6.902319e+08,0.050809,6.568575e+08,1.976276e+09,...,"[{'zone_number': 689, 'thickness': 1352754.233...",2.196107e+27,0.670584,0.000233,0.315703,0.000847,0.002347,0.006205,0.001380,0.002699
1406689411068933504,3,96,1.718444e+30,1.237558e+08,-0.044443,1.295117e+08,6.013815e+08,-0.044443,6.293521e+08,9.341452e+09,...,"[{'zone_number': 701, 'thickness': 1467654.211...",2.502973e+27,0.564256,0.000229,0.416813,0.000959,0.003500,0.008593,0.001912,0.003738
1403476981690082304,3,97,1.907885e+30,1.361816e+08,0.031577,1.320130e+08,8.186071e+08,0.031577,7.935491e+08,1.010472e+10,...,"[{'zone_number': 688, 'thickness': 1647831.249...",1.024522e+27,0.468930,0.000112,0.513408,0.000460,0.004175,0.007618,0.001792,0.003504
1392090267474126848,3,98,2.388658e+30,1.649205e+08,0.016488,1.622454e+08,1.127347e+09,0.016488,1.109061e+09,4.489689e+09,...,"[{'zone_number': 690, 'thickness': 1790586.412...",5.534411e+26,0.507219,0.000080,0.472924,0.000419,0.005313,0.008063,0.002025,0.003959
1392097311220494848,3,99,2.030161e+30,1.441265e+08,-0.033735,1.491583e+08,7.776789e+08,-0.033735,8.048298e+08,7.039093e+09,...,"[{'zone_number': 695, 'thickness': 1571266.601...",1.154234e+27,0.528624,0.000128,0.447513,0.000703,0.005195,0.010685,0.002420,0.004732

In [10]:
df_original = df
df_original

,batch_idx,iteration_idx,mass,core_radius,core_radius_error,original_core_radius,radius,radius_error,original_radius,age,...,burning_zones,he3_number_density,H,He3,He,C,N,O,Ne,Mg
2268469823008193152,0,0,1.637225e+30,1.179559e+08,-0.030944,1.217226e+08,5.890937e+08,-0.030944,6.079048e+08,1.299812e+10,...,"[{'zone_number': 697, 'thickness': 741941.5974...",2.482972e+27,0.527613,0.000213,0.453644,0.000878,0.003552,0.008506,0.001893,0.003701
2264752202396093440,0,1,1.621123e+30,1.188506e+08,0.021081,1.163968e+08,5.827517e+08,0.021081,5.707203e+08,1.114927e+10,...,"[{'zone_number': 696, 'thickness': 710542.9248...",2.835426e+27,0.552919,0.000242,0.433907,0.000684,0.002398,0.005943,0.001322,0.002586
2268087910219685504,0,10,1.445228e+30,1.009805e+08,-0.006525,1.016437e+08,4.962256e+08,-0.006525,4.994847e+08,1.233394e+10,...,"[{'zone_number': 704, 'thickness': 1505962.507...",4.950885e+27,0.580995,0.000380,0.402323,0.001233,0.002598,0.007527,0.001673,0.003271
1244590404650553600,0,100,1.895295e+30,1.382939e+08,0.063856,1.299931e+08,7.505098e+08,0.063856,7.054621e+08,7.745124e+09,...,"[{'zone_number': 692, 'thickness': 1474306.763...",1.487067e+27,0.539005,0.000155,0.446877,0.000525,0.002917,0.006308,0.001425,0.002787
6242646355272876928,0,101,1.823523e+30,1.321363e+08,-0.045321,1.384092e+08,6.934996e+08,-0.045321,7.264219e+08,9.557687e+09,...,"[{'zone_number': 695, 'thickness': 1503402.030...",1.612348e+27,0.525019,0.000157,0.457315,0.000648,0.003613,0.007968,0.001786,0.003493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406352685632976768,3,95,2.026285e+30,1.473643e+08,0.050809,1.402388e+08,6.902319e+08,0.050809,6.568575e+08,1.976276e+09,...,"[{'zone_number': 689, 'thickness': 1352754.233...",2.196107e+27,0.670584,0.000233,0.315703,0.000847,0.002347,0.006205,0.001380,0.002699
1406689411068933504,3,96,1.718444e+30,1.237558e+08,-0.044443,1.295117e+08,6.013815e+08,-0.044443,6.293521e+08,9.341452e+09,...,"[{'zone_number': 701, 'thickness': 1467654.211...",2.502973e+27,0.564256,0.000229,0.416813,0.000959,0.003500,0.008593,0.001912,0.003738
1403476981690082304,3,97,1.907885e+30,1.361816e+08,0.031577,1.320130e+08,8.186071e+08,0.031577,7.935491e+08,1.010472e+10,...,"[{'zone_number': 688, 'thickness': 1647831.249...",1.024522e+27,0.468930,0.000112,0.513408,0.000460,0.004175,0.007618,0.001792,0.003504
1392090267474126848,3,98,2.388658e+30,1.649205e+08,0.016488,1.622454e+08,1.127347e+09,0.016488,1.109061e+09,4.489689e+09,...,"[{'zone_number': 690, 'thickness': 1790586.412...",5.534411e+26,0.507219,0.000080,0.472924,0.000419,0.005313,0.008063,0.002025,0.003959
1392097311220494848,3,99,2.030161e+30,1.441265e+08,-0.033735,1.491583e+08,7.776789e+08,-0.033735,8.048298e+08,7.039093e+09,...,"[{'zone_number': 695, 'thickness': 1571266.601...",1.154234e+27,0.528624,0.000128,0.447513,0.000703,0.005195,0.010685,0.002420,0.004732

In [11]:
df = df_original[df_original['age_error'] >= 0]
df

,batch_idx,iteration_idx,mass,core_radius,core_radius_error,original_core_radius,radius,radius_error,original_radius,age,...,burning_zones,he3_number_density,H,He3,He,C,N,O,Ne,Mg
2268469823008193152,0,0,1.637225e+30,1.179559e+08,-0.030944,1.217226e+08,5.890937e+08,-0.030944,6.079048e+08,1.299812e+10,...,"[{'zone_number': 697, 'thickness': 741941.5974...",2.482972e+27,0.527613,0.000213,0.453644,0.000878,0.003552,0.008506,0.001893,0.003701
2264752202396093440,0,1,1.621123e+30,1.188506e+08,0.021081,1.163968e+08,5.827517e+08,0.021081,5.707203e+08,1.114927e+10,...,"[{'zone_number': 696, 'thickness': 710542.9248...",2.835426e+27,0.552919,0.000242,0.433907,0.000684,0.002398,0.005943,0.001322,0.002586
2268087910219685504,0,10,1.445228e+30,1.009805e+08,-0.006525,1.016437e+08,4.962256e+08,-0.006525,4.994847e+08,1.233394e+10,...,"[{'zone_number': 704, 'thickness': 1505962.507...",4.950885e+27,0.580995,0.000380,0.402323,0.001233,0.002598,0.007527,0.001673,0.003271
1244590404650553600,0,100,1.895295e+30,1.382939e+08,0.063856,1.299931e+08,7.505098e+08,0.063856,7.054621e+08,7.745124e+09,...,"[{'zone_number': 692, 'thickness': 1474306.763...",1.487067e+27,0.539005,0.000155,0.446877,0.000525,0.002917,0.006308,0.001425,0.002787
6242646355272876928,0,101,1.823523e+30,1.321363e+08,-0.045321,1.384092e+08,6.934996e+08,-0.045321,7.264219e+08,9.557687e+09,...,"[{'zone_number': 695, 'thickness': 1503402.030...",1.612348e+27,0.525019,0.000157,0.457315,0.000648,0.003613,0.007968,0.001786,0.003493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406352685632976768,3,95,2.026285e+30,1.473643e+08,0.050809,1.402388e+08,6.902319e+08,0.050809,6.568575e+08,1.976276e+09,...,"[{'zone_number': 689, 'thickness': 1352754.233...",2.196107e+27,0.670584,0.000233,0.315703,0.000847,0.002347,0.006205,0.001380,0.002699
1406689411068933504,3,96,1.718444e+30,1.237558e+08,-0.044443,1.295117e+08,6.013815e+08,-0.044443,6.293521e+08,9.341452e+09,...,"[{'zone_number': 701, 'thickness': 1467654.211...",2.502973e+27,0.564256,0.000229,0.416813,0.000959,0.003500,0.008593,0.001912,0.003738
1403476981690082304,3,97,1.907885e+30,1.361816e+08,0.031577,1.320130e+08,8.186071e+08,0.031577,7.935491e+08,1.010472e+10,...,"[{'zone_number': 688, 'thickness': 1647831.249...",1.024522e+27,0.468930,0.000112,0.513408,0.000460,0.004175,0.007618,0.001792,0.003504
1392090267474126848,3,98,2.388658e+30,1.649205e+08,0.016488,1.622454e+08,1.127347e+09,0.016488,1.109061e+09,4.489689e+09,...,"[{'zone_number': 690, 'thickness': 1790586.412...",5.534411e+26,0.507219,0.000080,0.472924,0.000419,0.005313,0.008063,0.002025,0.003959
1392097311220494848,3,99,2.030161e+30,1.441265e+08,-0.033735,1.491583e+08,7.776789e+08,-0.033735,8.048298e+08,7.039093e+09,...,"[{'zone_number': 695, 'thickness': 1571266.601...",1.154234e+27,0.528624,0.000128,0.447513,0.000703,0.005195,0.010685,0.002420,0.004732

In [12]:
_df = df.copy()

_df = _df[_df['reaction_rates_error'] <= 0.05]
_df = _df[_df['reaction_rates_error'] >= -0.05]

_df

,batch_idx,iteration_idx,mass,core_radius,core_radius_error,original_core_radius,radius,radius_error,original_radius,age,...,burning_zones,he3_number_density,H,He3,He,C,N,O,Ne,Mg
2268087910219685504,0,10,1.445228e+30,1.009805e+08,-0.006525,1.016437e+08,4.962256e+08,-0.006525,4.994847e+08,1.233394e+10,...,"[{'zone_number': 704, 'thickness': 1505962.507...",4.950885e+27,0.580995,0.000380,0.402323,0.001233,0.002598,0.007527,0.001673,0.003271
3876372503362913920,0,103,1.420969e+30,1.009755e+08,-0.013779,1.023862e+08,4.892375e+08,-0.013779,4.960726e+08,1.210798e+10,...,"[{'zone_number': 715, 'thickness': 1456642.525...",5.350726e+27,0.588225,0.000403,0.399059,0.000964,0.001926,0.005687,0.001264,0.002472
2268101727131230464,0,11,1.723568e+30,1.250814e+08,-0.011037,1.264774e+08,5.690351e+08,-0.011037,5.753857e+08,4.301907e+09,...,"[{'zone_number': 692, 'thickness': 700627.3420...",3.455792e+27,0.646871,0.000317,0.339211,0.000967,0.002239,0.006274,0.001395,0.002727
3895763112473649152,0,110,1.765144e+30,1.277347e+08,0.015933,1.257313e+08,7.205226e+08,0.015933,7.092223e+08,1.264748e+10,...,"[{'zone_number': 699, 'thickness': 1567201.386...",1.390638e+27,0.474575,0.000137,0.508616,0.000547,0.003637,0.007460,0.001701,0.003327
3662578102339135872,0,120,1.826111e+30,1.326846e+08,0.012678,1.310235e+08,6.846479e+08,0.012678,6.760765e+08,8.774010e+09,...,"[{'zone_number': 697, 'thickness': 1475731.026...",1.754598e+27,0.541868,0.000172,0.441337,0.000676,0.003346,0.007587,0.001697,0.003318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592334733874661248,3,82,1.666220e+30,1.206921e+08,0.009652,1.195383e+08,5.333423e+08,0.009652,5.282435e+08,2.049094e+09,...,"[{'zone_number': 699, 'thickness': 1390211.215...",4.608881e+27,0.691754,0.000421,0.296399,0.001125,0.001527,0.005295,0.001177,0.002301
3012028167748284800,3,86,1.482302e+30,1.074405e+08,-0.011068,1.086429e+08,5.028397e+08,-0.011068,5.084675e+08,8.986472e+09,...,"[{'zone_number': 703, 'thickness': 701406.8414...",5.069322e+27,0.613412,0.000402,0.376200,0.000783,0.001561,0.004613,0.001025,0.002005
1352382401469775744,3,87,1.673692e+30,1.230972e+08,0.009467,1.219428e+08,6.404413e+08,0.009467,6.344354e+08,1.220903e+10,...,"[{'zone_number': 696, 'thickness': 1455868.880...",2.080559e+27,0.516529,0.000188,0.470105,0.000573,0.002606,0.006022,0.001346,0.002631
1356125242130116864,3,91,1.654827e+30,1.210012e+08,0.014019,1.193283e+08,5.664350e+08,0.014019,5.586039e+08,7.294005e+09,...,"[{'zone_number': 702, 'thickness': 696906.0920...",3.365376e+27,0.606998,0.000294,0.380581,0.000762,0.002109,0.005585,0.001242,0.002428
1392090267474126848,3,98,2.388658e+30,1.649205e+08,0.016488,1.622454e+08,1.127347e+09,0.016488,1.109061e+09,4.489689e+09,...,"[{'zone_number': 690, 'thickness': 1790586.412...",5.534411e+26,0.507219,0.000080,0.472924,0.000419,0.005313,0.008063,0.002025,0.003959

In [13]:
he3_number_density_iqr = _df['he3_number_density'].quantile(0.75) - _df['he3_number_density'].quantile(0.25)
temperature_iqr = _df['core_temperature'].quantile(0.75) - _df['core_temperature'].quantile(0.25)
reaction_rates_iqr = _df['reaction_rates_per_unit_volume'].quantile(0.75) - _df[
    'reaction_rates_per_unit_volume'].quantile(0.25)

_df = _df[_df['he3_number_density'] >= df['he3_number_density'].quantile(0.25) - 1.5 * he3_number_density_iqr]
_df = _df[_df['core_temperature'] >= df['core_temperature'].quantile(0.25) - 1.5 * temperature_iqr]
_df = _df[_df['reaction_rates_per_unit_volume'] >= df['reaction_rates_per_unit_volume'].quantile(
    0.25) - 1.5 * reaction_rates_iqr]
_df = _df[_df['he3_number_density'] <= df['he3_number_density'].quantile(0.75) + 1.5 * he3_number_density_iqr]
_df = _df[_df['core_temperature'] <= df['core_temperature'].quantile(0.75) + 1.5 * temperature_iqr]
_df = _df[_df['reaction_rates_per_unit_volume'] <= df['reaction_rates_per_unit_volume'].quantile(
    0.75) + 1.5 * reaction_rates_iqr]

df_filtered = _df.copy()
_df

,batch_idx,iteration_idx,mass,core_radius,core_radius_error,original_core_radius,radius,radius_error,original_radius,age,...,burning_zones,he3_number_density,H,He3,He,C,N,O,Ne,Mg
2268101727131230464,0,11,1.723568e+30,1.250814e+08,-0.011037,1.264774e+08,5.690351e+08,-0.011037,5.753857e+08,4.301907e+09,...,"[{'zone_number': 692, 'thickness': 700627.3420...",3.455792e+27,0.646871,0.000317,0.339211,0.000967,0.002239,0.006274,0.001395,0.002727
3895763112473649152,0,110,1.765144e+30,1.277347e+08,0.015933,1.257313e+08,7.205226e+08,0.015933,7.092223e+08,1.264748e+10,...,"[{'zone_number': 699, 'thickness': 1567201.386...",1.390638e+27,0.474575,0.000137,0.508616,0.000547,0.003637,0.007460,0.001701,0.003327
3662578102339135872,0,120,1.826111e+30,1.326846e+08,0.012678,1.310235e+08,6.846479e+08,0.012678,6.760765e+08,8.774010e+09,...,"[{'zone_number': 697, 'thickness': 1475731.026...",1.754598e+27,0.541868,0.000172,0.441337,0.000676,0.003346,0.007587,0.001697,0.003318
4015518311198187392,0,124,1.549273e+30,1.132899e+08,0.011765,1.119726e+08,5.117721e+08,0.011765,5.058214e+08,5.205248e+09,...,"[{'zone_number': 700, 'thickness': 1374538.257...",5.052835e+27,0.654515,0.000424,0.335999,0.000772,0.001347,0.004190,0.000931,0.001821
4015792467550694528,0,125,1.678619e+30,1.224585e+08,0.009647,1.212884e+08,6.013956e+08,0.009647,5.956492e+08,1.013841e+10,...,"[{'zone_number': 699, 'thickness': 1440922.408...",2.527970e+27,0.554960,0.000222,0.429949,0.000736,0.002815,0.006827,0.001519,0.002971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592334733874661248,3,82,1.666220e+30,1.206921e+08,0.009652,1.195383e+08,5.333423e+08,0.009652,5.282435e+08,2.049094e+09,...,"[{'zone_number': 699, 'thickness': 1390211.215...",4.608881e+27,0.691754,0.000421,0.296399,0.001125,0.001527,0.005295,0.001177,0.002301
3012028167748284800,3,86,1.482302e+30,1.074405e+08,-0.011068,1.086429e+08,5.028397e+08,-0.011068,5.084675e+08,8.986472e+09,...,"[{'zone_number': 703, 'thickness': 701406.8414...",5.069322e+27,0.613412,0.000402,0.376200,0.000783,0.001561,0.004613,0.001025,0.002005
1352382401469775744,3,87,1.673692e+30,1.230972e+08,0.009467,1.219428e+08,6.404413e+08,0.009467,6.344354e+08,1.220903e+10,...,"[{'zone_number': 696, 'thickness': 1455868.880...",2.080559e+27,0.516529,0.000188,0.470105,0.000573,0.002606,0.006022,0.001346,0.002631
1356125242130116864,3,91,1.654827e+30,1.210012e+08,0.014019,1.193283e+08,5.664350e+08,0.014019,5.586039e+08,7.294005e+09,...,"[{'zone_number': 702, 'thickness': 696906.0920...",3.365376e+27,0.606998,0.000294,0.380581,0.000762,0.002109,0.005585,0.001242,0.002428
1392090267474126848,3,98,2.388658e+30,1.649205e+08,0.016488,1.622454e+08,1.127347e+09,0.016488,1.109061e+09,4.489689e+09,...,"[{'zone_number': 690, 'thickness': 1790586.412...",5.534411e+26,0.507219,0.000080,0.472924,0.000419,0.005313,0.008063,0.002025,0.003959

In [15]:
%matplotlib widget
x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']
y = np.log10(df_filtered['reaction_rates_per_unit_volume'])

count = 9
temp_range = np.linspace(temp.min(), temp.max(), count + 1)

frames = []


def format_title(value):
    # Get place value
    place_value = int(np.log10(value))
    if 4 <= place_value <= 6:
        return f'{round(value, -2) / 1000}K'
    elif 7 <= place_value <= 9:
        return f'{round(value, -4) / 10 ** 6}M'
    else:
        return f'{value:.1e}'


subplot_titles = [

]

letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

_last = temp.min()
idx = 0
for _temp in temp_range:
    if _temp == _last:
        continue
    subplot_titles.append(f'Temperature = {format_title(_last)} - {format_title(_temp)} C ({letters[idx]})')
    _last = _temp
    idx += 1

cols = 3
fig = make_subplots(rows=math.ceil((len(temp_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='He-3 Number Density (particles/m^3)', y_title='Reaction Rate (log(reactions/s/m^3))')

def update(a):
    if a.text =='He-3 Number Density (particles/m^3)' or a.text == 'Reaction Rate (log(reactions/s/m^3))':
        a.font.size = 20

fig.for_each_annotation(update)

last = temp.min()
row = 1
col = 1
for temp_value in temp_range:
    if temp_value == last:
        continue
    frame_df = df_filtered.copy()
    if temp_value == temp.max():
        frame_df = frame_df[frame_df['core_temperature'] <= temp_value]
    else:
        frame_df = frame_df[frame_df['core_temperature'] < temp_value]
    frame_df = frame_df[frame_df['core_temperature'] >= last]
    last = temp_value
    _x = frame_df['he3_number_density']
    _y = np.log10(frame_df['reaction_rates_per_unit_volume'])
    _temp = frame_df['core_temperature']
    fig.add_trace(go.Scatter(
        x=_x,
        y=_y,
        mode='markers',
        marker=dict(
            size=8,
            color='Blue',
            opacity=0.8,
            # colorbar=dict(title='Temperature (C)', len=0.8, thickness=20),
            # showscale=True,
            # coloraxis='coloraxis',
        ),
    ), row=row, col=col)

    col += 1
    if col > cols:
        col = 1
        row += 1

fig.update_layout(
    width=1600,
    height=1000,
    # coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Temperature (C)', len=0.8, thickness=20)),
    showlegend=False,
)

min_y = y.min() * 0.999
max_y = y.max() * 1.001

min_x = x.min() * 0.85
max_x = x.max() * 1.02

for i in range(len(temp_range)):
    param_name = f'yaxis{i + 1}'
    param_name_x = f'xaxis{i + 1}'
    if i == 0:
        param_name = 'yaxis'
        fig.update_layout(yaxis=dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')), xaxis=dict(title='Number Density', color='black', titlefont=dict(size=16, color='black')))
    elif i == 3:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], color='black'),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })
    elif i == 7:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(color='black')
        })
    else:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })

# Show the plot inline in Jupyter
pyo.iplot(fig)

## Run regressions

In [17]:
### Let's try a multi-variate regression
import pandas as pd
import statsmodels.api as sm

X = df_filtered[['he3_number_density', 'core_temperature']].copy()
X['log(he3_number_density)'] = np.log10(df_filtered['he3_number_density'])  # Need to log10 the number density because it's a gigantic number
X['log(he3_number_density)^2'] = np.log10(df_filtered['he3_number_density']) ** 2
temp = np.log10(df_filtered['reaction_rates_per_unit_volume'])

X['log(core_temperature)'] = np.log10(df_filtered['core_temperature'])
X['log(core_temperature)^2'] = np.log10(df_filtered['core_temperature']) ** 2
X['log(core_temperature)^3'] = np.log10(df_filtered['core_temperature']) ** 3

X = pd.concat([X['log(he3_number_density)'],X['log(he3_number_density)^2'], X['log(core_temperature)'],
               X['log(core_temperature)^2'], X['log(core_temperature)^3']], axis=1)

X = sm.add_constant(X)

model = sm.OLS(temp, X).fit()
model.summary()
# X

<class 'statsmodels.iolib.summary.Summary'>
"""
                                  OLS Regression Results
==========================================================================================
Dep. Variable:     reaction_rates_per_unit_volume   R-squared:                       0.640
Model:                                        OLS   Adj. R-squared:                  0.634
Method:                             Least Squares   F-statistic:                     113.1
Date:                            Sun, 05 Oct 2025   Prob (F-statistic):           2.21e-68
Time:                                    19:34:49   Log-Likelihood:                 806.06
No. Observations:                             324   AIC:                            -1600.
Df Residuals:                                 318   BIC:                            -1577.
Df Model:                                       5
Covariance Type:                        nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                     -5.365e+04   8394.741     -6.390      0.000   -7.02e+04   -3.71e+04
log(he3_number_density)       2.3758      5.963      0.398      0.691      -9.357      14.109
log(he3_number_density)^2    -0.0440      0.110     -0.401      0.688      -0.259       0.171
log(core_temperature)      2.264e+04   3562.488      6.356      0.000    1.56e+04    2.97e+04
log(core_temperature)^2   -3187.2893    502.650     -6.341      0.000   -4176.230   -2198.349
log(core_temperature)^3     149.5344     23.642      6.325      0.000     103.020     196.049
==============================================================================
Omnibus:                       67.458   Durbin-Watson:                   2.039
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              159.594
Skew:                           1.013   Prob(JB):                     2.21e-35
Kurtosis:                       5.778   Cond. No.                     6.70e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.94e-12. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [18]:
X['interaction'] = X['log(he3_number_density)'] * X['log(core_temperature)']

model_interaction = sm.OLS(temp, X).fit()
model_interaction.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                  OLS Regression Results
==========================================================================================
Dep. Variable:     reaction_rates_per_unit_volume   R-squared:                       0.692
Model:                                        OLS   Adj. R-squared:                  0.686
Method:                             Least Squares   F-statistic:                     118.4
Date:                            Sun, 05 Oct 2025   Prob (F-statistic):           6.78e-78
Time:                                    19:34:49   Log-Likelihood:                 831.08
No. Observations:                             324   AIC:                            -1648.
Df Residuals:                                 317   BIC:                            -1622.
Df Model:                                       6
Covariance Type:                        nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                      4431.6014   1.11e+04      0.397      0.691   -1.75e+04    2.64e+04
log(he3_number_density)   -1294.4705    178.333     -7.259      0.000   -1645.336    -943.605
log(he3_number_density)^2     9.4594      1.310      7.220      0.000       6.882      12.037
log(core_temperature)      9236.5885   3782.319      2.442      0.015    1794.968    1.67e+04
log(core_temperature)^2   -2031.0780    492.384     -4.125      0.000   -2999.832   -1062.324
log(core_temperature)^3     109.8984     22.587      4.866      0.000      65.460     154.337
interaction                 110.1146     15.135      7.276      0.000      80.337     139.892
==============================================================================
Omnibus:                       39.447   Durbin-Watson:                   2.063
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.977
Skew:                           0.605   Prob(JB):                     1.07e-20
Kurtosis:                       5.312   Cond. No.                     9.54e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.57e-12. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [27]:
## Use the model to make another surface plot
pio.templates.default = "plotly"

x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']

count = 25
x_space = np.linspace(x.min(), x.max(), 100)
temp_range = np.linspace(temp.min(), temp.max(), count + 1)

subplot_titles = []

_last = temp.min()
for _temp in temp_range:
    if _temp == _last:
        continue
    subplot_titles.append(f'Temperature = {format_title(_temp)} C')
    _last = _temp

cols = 5
fig = make_subplots(rows=math.ceil((len(temp_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='He-3 Number Density (particles/m^3)', y_title='Reaction Rate (log(reactions/s/m^3))')

max_y = 0
min_y = 1e10

last = temp.min()
idx = 0
row = 1
col = 1
for temp_value in temp_range:
    if temp_value == last:
        continue
    frame_df = df_filtered.copy()
    if temp_value == temp.max():
        frame_df = frame_df[frame_df['core_temperature'] <= temp_value]
    else:
        frame_df = frame_df[frame_df['core_temperature'] < temp_value]
    frame_df = frame_df[frame_df['core_temperature'] >= last]
    last = temp_value

    fig.add_trace(
        go.Scatter(x=frame_df['he3_number_density'], y=np.log10(frame_df['reaction_rates_per_unit_volume']), mode='markers',
                   marker=dict(
                       # color=frame_df['core_temperature'],
                       size=8,
                       opacity=0.8,
                       color="Blue"
                       # colorbar=dict(title='Temperature (C)', len=0.8, thickness=20),
                       # showscale=True,
                       # coloraxis='coloraxis',
                   )),
        row=row, col=col
    )

    _x = frame_df['he3_number_density']
    x_space = np.linspace(.97 * _x.min(), _x.max() * 1.03, 100)

    temp_space = np.array([temp_value] * len(x_space))
    if len(_x) == 1:
        x_value = _x.iloc[0]
        x_space = np.linspace(x_value * 0.97, x_value * 1.03, 100)
        temp_space = np.array(frame_df['core_temperature'].iloc[0]) * np.ones_like(x_space)

    input_data = pd.DataFrame(
        {
            'const': np.ones_like(x_space),
            'log(he3_number_density)': np.log10(x_space),
            'log(he3_number_density)^2': np.log10(x_space) ** 2,
            'log(core_temperature)': np.log10(temp_space),
            'log(core_temperature)^2': np.log10(temp_space) ** 2,
            'log(core_temperature)^3': np.log10(temp_space) ** 3,
            'interaction': np.log10(x_space) * np.log10(temp_space),
        }
    )

    ys = model_interaction.predict(input_data).values
    fig.add_trace(
        go.Scatter(x=x_space, y=ys, mode='lines', marker=dict(color='red')),
        row=row, col=col
    )

    max_y = max(max_y, ys.max())
    min_y = min(min_y, ys.min())

    col += 1
    if col > cols:
        col = 1
        row += 1

    idx += 1

fig.update_layout(
    width=2400,
    height=2000,
    showlegend=False,
    coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Temperature (C)', len=0.8, thickness=20)),
)

min_y = min_y * 0.999
max_y = max_y * 1.0025


for i in range(len(temp_range)):
    param_name = f'yaxis{i + 1}'
    param_name_x = f'xaxis{i + 1}'
    if i == 0:
        param_name = 'yaxis'
        fig.update_layout(yaxis=dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')), xaxis=dict(title='Number Density', color='black', titlefont=dict(size=16, color='black')))
    elif i == 10:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], color='black'),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })
    elif i == 22:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(color='black')
        })
    else:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })


def update(a):
    if a.text =='He-3 Number Density (particles/m^3)' or a.text == 'Reaction Rate (log(reactions/s/m^3))':
        a.font.size = 20

fig.for_each_annotation(update)

fig.show()

In [21]:
## Use the model to make another surface plot
import statsmodels.api as sm

pio.templates.default = "plotly"

x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']

count = 25
x_space = np.linspace(x.min(), x.max(), 100)
temp_range = np.linspace(temp.min(), temp.max(), count + 1)

subplot_titles = []

_last = temp.min()
idx = 1
for _temp in temp_range:
    if _temp == _last:
        continue
    subplot_titles.append(f'Temperature = {format_title(_temp)} C')
    _last = _temp
    idx += 1

cols = 5
fig = make_subplots(rows=math.ceil((len(temp_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='He-3 Number Density (particles/m^3)', y_title='Reaction Rate (log(reactions/s/m^3))')

def update(a):
    if a.text =='He-3 Number Density (particles/m^3)' or a.text == 'Reaction Rate (log(reactions/s/m^3))':
        a.font.size = 20

fig.for_each_annotation(update)

max_y = 0
min_y = 1e10

last = temp.min()
idx = 0
row = 1
col = 1
for temp_value in temp_range:
    if temp_value == last:
        continue
    frame_df = df_filtered.copy()
    if temp_value == temp.max():
        frame_df = frame_df[frame_df['core_temperature'] <= temp_value]
    else:
        frame_df = frame_df[frame_df['core_temperature'] < temp_value]
    frame_df = frame_df[frame_df['core_temperature'] >= last]
    last = temp_value

    # fig.add_trace(
    #     go.Scatter(x=frame_df['he3_number_density'], y=np.log10(frame_df['reaction_rates_per_unit_volume']), mode='markers',
    #                marker=dict(
    #                    color=frame_df['core_temperature'],
    #                    size=8,
    #                    opacity=0.8,
    #                    colorbar=dict(title='Temperature (C)', len=0.8, thickness=20),
    #                    showscale=True,
    #                    coloraxis='coloraxis',
    #                )),
    #     row=row, col=col
    # )

    # _x = frame_df['he3_number_density']
    # x_space = np.linspace(.9 * _x.min(), _x.max() * 1.1, 100)

    temp_space = np.array([temp_value] * len(x_space))
    # if len(_x) == 1:
    #     x_value = _x.iloc[0]
    #     x_space = np.linspace(x_value * 0.9, x_value * 1.1, 100)
    #     temp_space = np.array(frame_df['core_temperature'].iloc[0]) * np.ones_like(x_space)

    input_data = pd.DataFrame(
        {
            'const': np.ones_like(x_space),
            'log(he3_number_density)': np.log10(x_space),
            'log(he3_number_density)^2': np.log10(x_space) ** 2,
            'log(core_temperature)': np.log10(temp_space),
            'log(core_temperature)^2': np.log10(temp_space) ** 2,
            'log(core_temperature)^3': np.log10(temp_space) ** 3,
            'interaction': np.log10(x_space) * np.log10(temp_space),
        }
    )

    ys = model_interaction.predict(input_data).values
    fig.add_trace(
        go.Scatter(x=x_space, y=ys, mode='lines', marker=dict(color='red')),
        row=row, col=col
    )

    max_y = max(max_y, ys.max())
    min_y = min(min_y, ys.min())

    col += 1
    if col > cols:
        col = 1
        row += 1

    idx += 1

fig.update_layout(
    width=2000,
    height=2000,
    showlegend=False,
    coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Temperature (C)', len=0.8, thickness=20)),
)

min_y = min_y * 0.999
max_y = max_y * 1.0025

for i in range(len(temp_range)):
    param_name = f'yaxis{i + 1}'
    param_name_x = f'xaxis{i + 1}'
    if i == 0:
        param_name = 'yaxis'
        fig.update_layout(yaxis=dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')), xaxis=dict(title='Number Density', color='black', titlefont=dict(size=16, color='black')))
    elif i == 10:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], color='black'),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })
    elif i == 22:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(color='black')
        })
    else:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })

fig.show()

In [23]:
## Use the model to make another surface plot
import statsmodels.api as sm

x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']

count = 25
number_density_range = np.linspace(x.min(), x.max(), count + 1)
x_space = np.linspace(temp.min(), temp.max(), 100)

subplot_titles = []

_last = number_density_range.min()
for _num_density in number_density_range:
    if _num_density == _last:
        continue
    subplot_titles.append(f'n = {format_title(_num_density)} atoms/m^3')
    _last = _num_density

cols = 6
fig = make_subplots(rows=math.ceil((len(number_density_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='Core Temperature (C)', y_title='Reaction Rate (log(reactions/s/m^3))')

def update(a):
    if a.text =='He-3 Number Density (particles/m^3)' or a.text == 'Reaction Rate (log(reactions/s/m^3))':
        a.font.size = 20

fig.for_each_annotation(update)

max_y = 0
min_y = 1e10

last = number_density_range.min()
idx = 0
row = 1
col = 1
for number_density in number_density_range:
    if number_density == last:
        continue

    frame_df = df_filtered.copy()
    if number_density == number_density_range.max():
        frame_df = frame_df[frame_df['he3_number_density'] <= number_density]
    else:
        frame_df = frame_df[frame_df['he3_number_density'] < number_density]
    frame_df = frame_df[frame_df['he3_number_density'] >= last]
    last = number_density

    _x = frame_df['core_temperature']
    x_space = np.linspace(_x.min(), _x.max(), 100)

    if len(_x) == 1:
        x_value = _x.iloc[0]
        x_space = np.linspace(x_value * 0.9, x_value * 1.1, 100)

    he3_number_density_space = np.array([number_density] * len(x_space))
    input_data = pd.DataFrame(
        {
            'const': np.ones_like(x_space),
            'log(he3_number_density)': np.log10(he3_number_density_space),
            'log(he3_number_density)^2': np.log10(he3_number_density_space) ** 2,
            'log(core_temperature)': np.log10(x_space),
            'log(core_temperature)^2': np.log10(x_space) ** 2,
            'log(core_temperature)^3': np.log10(x_space) ** 3,
            'interaction': np.log10(he3_number_density_space) * np.log10(x_space),
        }
    )

    ys = model_interaction.predict(input_data).values
    fig.add_trace(
        go.Scatter(x=x_space, y=10 ** ys, mode='lines', marker=dict(color='red')),
        row=row, col=col
    )

    fig.add_trace(
        go.Scatter(x=frame_df['core_temperature'], y=(frame_df['reaction_rates_per_unit_volume']),
                   mode='markers', marker=dict(
                color=frame_df['he3_number_density'],
                size=8,
                opacity=0.8,
                colorbar=dict(title='Number Density (atoms/m^3)', len=0.8, thickness=20),
                showscale=True,
                coloraxis='coloraxis',
            )),
        row=row, col=col
    )

    # max_y = max(max_y, ys.max())
    # min_y = min(min_y, ys.min())

    col += 1
    if col > cols:
        col = 1
        row += 1

    idx += 1

fig.update_layout(
    width=1600,
    height=1200,
    showlegend=False,
    coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Density (kg/m^3)', len=0.8, thickness=20)),
)

# max_y = max_y * 1.005
#
# for i in range(count):
#     param_name = f'yaxis{i + 1}'
#     if i == 0:
#         param_name = 'yaxis'
#         fig.update_layout(yaxis=dict(range=[min_y, max_y]))
#
#     else:
#         fig.update_layout({
#             param_name: dict(range=[min_y, max_y])
#         })

fig.show()

In [26]:
## Residuals
import statsmodels.api as sm

pio.templates.default = "plotly"

x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']

count = 25
temp_range = np.linspace(temp.min(), temp.max(), count + 1)

subplot_titles = []

_last = temp.min()
for _temp in temp_range:
    if _temp == _last:
        continue
    subplot_titles.append(f'Temperature = {format_title(_temp)} C')
    _last = _temp

cols = 5
fig = make_subplots(rows=math.ceil((len(temp_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='He-3 Number Density (particles/m^3)', y_title='Reaction Rate (log(reactions/s/m^3))')


def update(a):
    if a.text =='He-3 Number Density (particles/m^3)' or a.text == 'Reaction Rate (log(reactions/s/m^3))':
        a.font.size = 20

fig.for_each_annotation(update)

min_x = df_filtered['he3_number_density'].min() * .98
max_x = df_filtered['he3_number_density'].max() * 1.02

last = temp_range.min()
idx = 0
row = 1
col = 1
for temp_value in temp_range:
    if temp_value == last:
        continue

    frame_df = df_filtered.copy()
    if temp_value == temp_range.max():
        frame_df = frame_df[frame_df['core_temperature'] <= temp_value]
    else:
        frame_df = frame_df[frame_df['core_temperature'] < temp_value]
    frame_df = frame_df[frame_df['core_temperature'] >= last]
    last = temp_value

    input_data = pd.DataFrame(
        {
            'const': np.ones(len(frame_df['core_density'])),
            'log(he3_number_density)': np.log10(frame_df['he3_number_density']),
            'log(he3_number_density)^2': np.log10(frame_df['he3_number_density']) ** 2,
            'log(core_temperature)': np.log10(frame_df['core_temperature']),
            'log(core_temperature)^2': np.log10(frame_df['core_temperature']) ** 2,
            'log(core_temperature)^3': np.log10(frame_df['core_temperature']) ** 3,
            'interaction': np.log10(frame_df['he3_number_density']) * np.log10(frame_df['core_temperature']),
        }
    )

    ys = model_interaction.predict(input_data).values

    residuals = np.log10(frame_df['reaction_rates_per_unit_volume']) - ys

    fig.add_trace(
        go.Scatter(x=frame_df['he3_number_density'], y=residuals, mode='markers', marker=dict(
            color='Blue',
            size=8,
            opacity=0.8,
            # colorbar=dict(title='Temperature (C)', len=0.8, thickness=20),
            # showscale=True,
            # coloraxis='coloraxis',
        )),
        row=row, col=col
    )

    _min_x = frame_df['he3_number_density'].min() * 0.9
    _max_x = frame_df['he3_number_density'].max() * 1.1

    fig.add_trace(
        go.Scatter(x=[_min_x, _max_x], y=[0, 0], mode='lines', marker=dict(color='black'), name='Middle',
                   line=dict(dash='dash')),
        row=row, col=col
    )

    col += 1
    if col > cols:
        col = 1
        row += 1

    idx += 1

fig.update_layout(
    width=2400,
    height=2000,
    showlegend=False,
    # coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Temperature (C)', len=0.8, thickness=20)),
    yaxis=dict(range=[-0.08, 0.08]),
    # xaxis=dict(range=[min_x, max_x]),
)

min_y = -0.08
max_y = 0.08

for i in range(len(temp_range)):
    param_name = f'yaxis{i + 1}'
    param_name_x = f'xaxis{i + 1}'
    if i == 0:
        param_name = 'yaxis'
        fig.update_layout(yaxis=dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')), xaxis=dict(title='Number Density', color='black', titlefont=dict(size=16, color='black')))
    elif i == 10:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], color='black'),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })
    elif i == 22:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(color='black')
        })
    else:
        fig.update_layout({
            param_name: dict(range=[min_y, max_y], title='Reaction Rates', color='black', titlefont=dict(size=16, color='black')),
            param_name_x: dict(title='Number Density', color='black', titlefont=dict(size=16, color='black'))
        })

fig.show()

In [84]:
## Residuals
import statsmodels.api as sm

pio.templates.default = "plotly"

x = df_filtered['he3_number_density']
temp = df_filtered['core_temperature']

count = 25
number_density_range = np.linspace(number_density_range.min(), number_density_range.max(), count + 1)

subplot_titles = []

_last = number_density_range.min()
for _num_density in number_density_range:
    if _num_density == _last:
        continue
    subplot_titles.append(f'n = {format_title(_num_density)} atoms/m^3')
    _last = _num_density

cols = 5
fig = make_subplots(rows=math.ceil((len(temp_range) - 1) / cols), cols=cols, subplot_titles=subplot_titles,
                    x_title='He-3 Number Density (atoms/m^3)', y_title='Reaction Rate (log(reactions/s/m^3))')

# max_x = temp.max() * 1.02
# min_x = temp.min() * .98

last = number_density_range.min()
idx = 0
row = 1
col = 1
for num_density in number_density_range:
    if num_density == last:
        continue

    frame_df = df_filtered.copy()
    if num_density == number_density_range.max():
        frame_df = frame_df[frame_df['he3_number_density'] <= num_density]
    else:
        frame_df = frame_df[frame_df['he3_number_density'] < num_density]
    frame_df = frame_df[frame_df['he3_number_density'] >= last]
    last = num_density

    input_data = pd.DataFrame(
        {
            'const': np.ones(len(frame_df['he3_number_density'])),
            'log(he3_number_density)': np.log10(frame_df['he3_number_density']),
            'log(he3_number_density)^2': np.log10(frame_df['he3_number_density']) ** 2,
            'log(core_temperature)': np.log10(frame_df['core_temperature']),
            'log(core_temperature)^2': np.log10(frame_df['core_temperature']) ** 2,
            'log(core_temperature)^3': np.log10(frame_df['core_temperature']) ** 3,
            'interaction': np.log10(frame_df['he3_number_density']) * np.log10(frame_df['core_temperature']),
        }
    )

    ys = model_interaction.predict(input_data).values

    residuals = np.log10(frame_df['reaction_rates_per_unit_volume']) - ys

    fig.add_trace(
        go.Scatter(x=frame_df['core_temperature'], y=residuals, mode='markers', marker=dict(
            color=frame_df['he3_number_density'],
            size=8,
            opacity=0.8,
            colorbar=dict(title='Number Density (atoms/m^3)', len=0.8, thickness=20),
            showscale=True,
            coloraxis='coloraxis',
        )),
        row=row, col=col
    )

    _min_x = frame_df['core_temperature'].min() * 0.99
    _max_x = frame_df['core_temperature'].max() * 1.01

    fig.add_trace(
        go.Scatter(x=[_min_x, _max_x], y=[0, 0], mode='lines', marker=dict(color='black'), name='Middle',
                   line=dict(dash='dash')),
        row=row, col=col
    )

    col += 1
    if col > cols:
        col = 1
        row += 1

    idx += 1

fig.update_layout(
    title='Residuals of Reaction Rates vs. Core Temperature with varying number density',
    width=1600,
    height=1000,
    showlegend=False,
    coloraxis=dict(colorscale='BlueRed', colorbar=dict(title='Number Density (atoms/m^3)', len=0.8, thickness=20)),
    # yaxis=dict(range=[-0.05, 0.08]),
    # xaxis=dict(range=[min_x, max_x]),
)

# for i in range(count):
#     param_name = f'yaxis{i + 1}'
#     param_name_x = f'xaxis{i + 1}'
#     if i == 0:
#         pass
#     else:
#         fig.update_layout({
#             param_name_x: dict(range=[min_x, max_x]),
#             param_name: dict(range=[-0.05, 0.08])
#         })

fig.show()

NameError: name 'number_density_range' is not defined

In [ ]:
_x = df_filtered['he3_number_density']
_y = df_filtered['core_temperature']
_z = model_interaction.resid

x_space = np.linspace(_x.min(), _x.max(), 100)
y_space = np.linspace(_y.min(), _y.max(), 100)

x_grid, y_grid = np.meshgrid(x_space, y_space)

fig = go.Figure(
    data=[
        go.Scatter(
            x=_x,
            y=_z,
            mode='markers',
            marker=dict(
                size=8,
                color=_z,
                colorscale='balance',
                opacity=0.8,
            ),
        ),
        # go.Surface(x=x_grid, y=y_grid, z=np.zeros_like(x_grid), opacity=0.5, showscale=False, colorscale="Reds"),
    ]
)

fig.update_layout(
    title='Residuals vs. He-3 Number Density and Temperature',
    # scene=dict(
    #     xaxis_title='He-3 Number Density (particles/m^3)',
    #     yaxis_title='Temperature (K)',
    #     zaxis_title='Residuals',
    # ),
    width=1200,
    height=1000,
)

fig.show()

# Final equation:

$$
\begin{align*}
\log{\hat{y}} = &-1294.470482\log(n) \\
&+ 9.459420\log(n)^2 \\
&+ 9236.588515\log{T}  \\
&- 2031.078040\log({T})^2  \\
&+ 109.898367\log({T})^3 \\
&+ 110.114593(\log(n) \cdot \log{T}) \\
&- 4431.601421
\end{align*}
$$